### ISSUE TITLE
Revamp the `README.md` with a lick of paint 🎨 

### ISSUE THREAD

**Issue by JamieSlome** [finos/git-proxy#177]
The `README.md` needs a lick of paint to reflect some of the latest improvements and changes.

```[tasklist]
### Tasks
- [ ] Add more [badges](https://shields.io) for license, forks, stars and npm package
- [ ] Revamp the `README.md` using the [following format](https://github.com/othneildrew/Best-README-Template)
- [ ] Provide simple installation and get-started instructions
```
