### ISSUE TITLE
Implement best ESLINT and Prettier combo with auto save 💪 

### ISSUE THREAD

**Issue by JamieSlome** [finos/git-proxy#193]
Currently, the ESLINT and Prettier setup is not sufficient for enforcing code cleanliness or readable files.

```[tasklist]
### Tasks
- [ ] Install the most relevant ESLINT and Prettier modules for the project
- [ ] Create a set of scripts in the `package.json` to mass lint and prettify
- [ ] Ensure ESLINT and Prettier warnings are visible in IDE
- [ ] Auto linting and pretty on save
- [ ] Bonus points 🏆 - create a GitHub Action to validate all files are linted and pretty
```

**Comment by vaibssingh** [comment]
@JamieSlome Can I take this up?

**Comment by JamieSlome** [comment]
@vaibssingh - all yours! 🤝

**Comment by vaibssingh** [comment]
Hey @JamieSlome, for the PR with the new eslint config, should I also include all the files that have been modified because of the new rules or should that be a separate PR?

Right now due to the enforced rules, there are some breaking changes like removing ```require``` and updating the ```import/export``` methods in lot of files.

For reference, this is what the modified ```eslintrc.js``` file currently looks like:

```
module.exports = {
  env: {
    browser: true,
    commonjs: true,
    es2021: true,
    node: true,
  },
  extends: ['plugin:react/recommended', 'prettier', 'google'],
  parserOptions: {
    ecmaFeatures: {
      jsx: true,
    },
    ecmaVersion: 12,
  },
  plugins: ['prettier', 'react'],
  rules: {
    'prettier/prettier': ['error', { singleQuote: true }],
    'object-curly-spacing': ['error', 'always'],
    'space-before-function-paren': 'off',
    'quote-props': [
      'error',
      'as-needed',
      { keywords: false, unnecessary: true, numbers: false },
    ],
    indent: 'off',
  },
};
```
I have also added ```type: module``` in ```package.json``` to make it compatible with ES module ```import/export``` used in majority of the files.

Let me know how you want me to proceed with this 😄

**Comment by JamieSlome** [comment]
@vaibssingh - thanks for the update.

I'd recommend including the file changes in the same PR.

Feel free to open the PR once you are ready to go 🚀

**Comment by JamieSlome** [comment]
@vaibssingh - thank you very much for your contribution! 🎉 

You achieved this task to spec and have delivered a key support mechanism for developers that will contribute to Git Proxy in the future.

I look forward to your future contributions 👏
