### ISSUE TITLE
Reconcile changes on `mvp` branch with `main`

### ISSUE THREAD

**Issue by JamieSlome** [finos/git-proxy#201]
A significant number of changes were made to the library in the `mvp` branch. Are we able to reconcile the latest changes to `main` with the changes made on the `mvp` branch?

@grovesy @maoo - any help from your end would be appreciated as a lot of this code was created before my time 😆 

```[tasklist]
### Tasks
- [x] Open a pull request from `mvp` to `main`
- [ ] Merge in `main` latest changes to `mvp`
- [ ] Resolve merge conflicts (no doubt there will be loads)
```

**Comment by maoo** [comment]
@JamieSlome - Is there anything else that needs to be merged from https://github.com/finos/git-proxy/branches ?

**Comment by JamieSlome** [comment]
No longer relevant. Being addressed by #335 👍
