### ISSUE TITLE
Increase test coverage to 80% ⚡️ 

### ISSUE THREAD

**Issue by JamieSlome** [finos/git-proxy#240]
The codebase currently has low test coverage. To ensure the stability of the library and speed up pull request reviews, the test coverage should be increased to a common standard of 80%.

Code coverage reports are currently being developed in #203.

```[tasklist]
### Tasks
- [ ] Create test files in `test` folder
- [ ] Run `nyc` to understand the current test score and code areas requiring more test coverage
- [ ] Ensure all files reported by `nyc` have at least 80% coverage on all code aspects (functions, lines, etc.)
```

**Comment by IshwaryaSriram** [comment]
Hi @JamieSlome, I would like to contribute to increasing test coverage.

**Comment by JamieSlome** [comment]
@IshwaryaSriram - all yours 🙌
