### ISSUE TITLE
Design quick-start installation, usage and happy path documentation

### ISSUE THREAD

**Issue by JamieSlome** [finos/git-proxy#296]
To support #287 and the release of [v1.1.0](https://github.com/finos/git-proxy/releases/tag/v1.1.0), a simple and easy-to-follow set of instructions need to be included in the `README.md` and `docs`.

```[tasklist]
### Tasks
- [x] Add a clear documentation badge at the top of the `README.md`
- [x] Add simple instructions for installing the library and using it in a local environment
- [x] Include simple instructions for reproducing a happy path of a custom authorized repository
- [x] Explain how to store git credentials on the client to prevent excessive manual authentication per push
- [x] Add the above steps to the documentation website
```
