### ISSUE TITLE
Implement a CI step to detect unused dependencies 📦 

### ISSUE THREAD

**Issue by JamieSlome** [finos/git-proxy#413]
To ensure we don't unnecessarily hit "dependency bloat" nor merge pull requests with dependencies that are unused, we should introduce a GitHub Action or CI step to detect which dependencies are unused. This is a great first issue for someone looking to make their first contribution to the project 🎉 

```[tasklist]
### Tasks
- [x] Detect unused dependencies and fail CI if more than 0
- [x] Detect unused `dependencies` and `devDependencies`
- [x] Only allow PR merges if the Action or CI step returns safely
```

I have previously come across [depcheck](https://www.npmjs.com/package/depcheck) - a nice lightweight NPM library that discovers unused dependencies.

**Comment by JamieSlome** [comment]
@marksmith388 - would you be interested in picking this one up? 🤔

**Comment by JamieSlome** [comment]
@tt-gideonaryeetey and @divinetettey - asked discussed, are you interested in picking this issue up? Let me know below and then I can assign to you if you're happy to 👍

**Comment by divinetettey** [comment]
Hi @JamieSlome   yes I would pick this issue

**Comment by JamieSlome** [comment]
Achieved in #592. You're a rockstar @divinetettey 🚀
