### ISSUE TITLE
Run GitHub Dependency Review on pull request 🔍

### ISSUE THREAD

**Issue by JamieSlome** [finos/git-proxy#491]
```[tasklist]
### Tasks
- [x] Create a workflow file in `.github/workflows`
- [x] Use the default setup from [GitHub Docs](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/configuring-dependency-review)
- [x] Deprecate duplicative workflows and apps installed on the repository
```
