### ISSUE TITLE
Updated required status checks for pull request to be merged ✅ 

### ISSUE THREAD

**Issue by JamieSlome** [finos/git-proxy#519]
As discussed in our community call today, we do not want to block pull request merges if an warning is raised by a status check that is outside of the scope of the changes proposed by the contributor. https://github.com/finos/git-proxy/pull/482 is a good demonstration of this. @msagi has completed the pull request yet is being warned by the Dependency Review status check that a dependency (`caniuse-lite`) has an non-compliant license for the project.

I would suggest that we treat all status checks that are **required** as non-negotiable prior to PR merge, and those that are not listed as **required** can be merged if all others are passing successfully.

The following status checks should be set to **Required**:

```[tasklist]
### Tasks
- [x] CI set as required status check
- [x] Code Cleanliness set as a required status check
- [x] EasyCLA set as a required status check
- [x] Remove CodeQL scanning results as a required status check
```

Thank you @msagi @coopernetes for your opine on this issue 🍰 One byte at a time!

**Comment by maoo** [comment]
Attaching screenshot. @JamieSlome - did I get it right?

<img width="745" alt="Screenshot 2024-04-08 at 22 08 57" src="https://github.com/finos/git-proxy/assets/327285/50ce658b-e8ff-4e83-8195-48040430e09f">

**Comment by JamieSlome** [comment]
@maoo - looking at #482, it appears that only EasyCLA is presenting as **required**. Tangental, but is there a reason maintainers are not allowed administrative control over the repository?

**Comment by JamieSlome** [comment]
@maoo - the last commit on the pull request was 2 hours ago. The latest status checks are showing only EasyCLA as **required**. 

It would be great to have admin rights to be able to affect these changes without having to ask the FINOS team to execute on them, especially if they are experimental in nature. I'll ping an e-mail over - thank you @maoo ❤️

**Comment by JamieSlome** [comment]
Done 🎉 

<img width="758" alt="Screenshot 2024-04-09 at 14 35 41" src="https://github.com/finos/git-proxy/assets/55323451/40e71944-70e0-4cae-b980-e60e740961e5">

Closing this issue as completed 👍
