### ISSUE TITLE
Add demo video to docs site and `README.md` 🎥 

### ISSUE THREAD

**Issue by JamieSlome** [finos/git-proxy#617]
Getting to grasps with the purpose of any project can be challenging. By republishing a demo of GitProxy on our docs site (in the hero) and in plain view on our `README.md` we will cast a wider net for passers by to get to grips with GitProxy 👍 

```[tasklist]
### Tasks
- [x] Add a watch a demo button in the website hero
- [x] Add a demo section with link to the video in the `README.md`
- [x] Use the [OSR demo](https://www.finos.org/hubfs/Projects%20%2B%20SIGs/Open%20Source%20Readiness%20OSR/OSR%20Meeting_%20GitProxy%20Jamie%20Slome%20Citi%20Presentation.mp4) as the video source
```
