### ISSUE TITLE
Run a hosted demo of the GitProxy dashboard ☁️ 

### ISSUE THREAD

**Issue by JamieSlome** [finos/git-proxy#627]
It would be fab for newcomers (both contributors and users) of GitProxy to quickly get to grasps with the purpose and impact of the project. Whilst not all users will take advantage or use the dashboard, it is certainly helpful to understand the concept of GitProxy and its endless capability as a self deployed interception point for git traffic.

```[tasklist]
### Tasks
- [ ] Build and run the latest version of `@finos/git-proxy` from our microsite
- [ ] Attach the demo to the `/demo` endpoint of the site
- [ ] Consider security implications of a deployed demo in the comments below
```

**Comment by laukik-target** [comment]
@JamieSlome Hi, By the title I was not clear with the objective.

When you say "Attach the demo to the /demo endpoint of the site"
What exactly is the expectation of the demo? I am not clear. Can you please elaborate or explain the requirement more clearly?
